@startuml

title __MODEL's Class Diagram__\n

    namespace Model {
      class Model.Agregador {
          - estados : List<Estado>
          {static} - instance : Agregador
          - lastProcesses : ObservableList<Process>
          - lock : ReentrantLock
          + addEstado()
          + getEstados()
          + getFirstProcessUptime()
          {static} + getInstance()
          + getLastCPUTotal()
          + getLastMEMTotal()
          + getLastProcessUptime()
          + getLastProcesses()
          + getProcessGroupByName()
          + getTotalTimeProcess()
          - Agregador()
      }
    }

    namespace Model {
      class Model.Estado {
          - cpuTotal : Double
          - processos : Map<Integer, Process>
          - ramTotal : Double
          - uptime : String
          + Estado()
          + addProcess()
          + containsPID()
          + getCpuTotal()
          + getProcessesByName()
          + getProcessos()
          + getRamTotal()
          + getUptime()
          + setCpuTotal()
          + setRamTotal()
          + setUptime()
      }
    }

    namespace Model {
      class Model.Log {
          ~ path : String
          - br : BufferedReader
          - running : boolean
          + Log()
          + init()
          + open()
          + read()
      }
    }


    namespace Model {
      class Model.Process {
          - cpu : Double
          - mem : Double
          - name : String
          - pid : Integer
          + Process()
          + getCpu()
          + getMem()
          + getName()
          + getPid()
      }
    }
  

    namespace Model {
      class Model.ProcessGroup {
          - cpu : Double
          - mem : Double
          - name : String
          - pid : Integer
          - uptime : Long
          + ProcessGroup()
          + getCpu()
          + getMem()
          + getName()
          + getPid()
          + getUptime()
          + setCpu()
          + setMem()
          + setName()
          + setPid()
          + setUptime()
      }
    }

  

    namespace Model {
      class Model.Tradutor {
          {static} + linhaProcess()
          {static} + linhaToUptime()
          {static} - getCPU()
          {static} - getName()
          {static} - getPID()
          {static} - getRAM()
      }
    }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
