@startuml

title __CONTROLLER's Class Diagram__\n

  namespace  {
    namespace ontroller {
      class Controller.ControllerCPU {
          - chart : AreaChart<String, Number>
          - xAxis : CategoryAxis
          - yAxis : NumberAxis
          + initialize()
      }
    }
  }
  

  namespace  {
    namespace ontroller {
      class Controller.ControllerInfo {
          - cpu : TableColumn<ProcessGroup, Number>
          - loading : ProgressIndicator
          - mem : TableColumn<ProcessGroup, Number>
          - name : TableColumn<ProcessGroup, String>
          - pid : TableColumn<ProcessGroup, Number>
          - processos : TableView<ProcessGroup>
          - searchName : TextField
          - uptime : TableColumn<ProcessGroup, Number>
          ~ doIT()
          ~ search()
      }
    }
  }
  

  namespace  {
    namespace ontroller {
      class Controller.ControllerMain {
          - file : Button
          - progress : ProgressIndicator
          - start : Button
          ~ chooseFile()
          ~ start()
      }
    }
  }
  

  namespace  {
    namespace ontroller {
      class Controller.ControllerMem {
          - chart : AreaChart<String, Number>
          - xAxis : CategoryAxis
          - yAxis : NumberAxis
          + initialize()
      }
    }
  }
  

  namespace  {
    namespace ontroller {
      class Controller.ControllerUI {
          - PID : TableColumn<Process, Integer>
          - cpu : TableColumn<Process, Double>
          - cpuG : Gauge
          - infoText : Label
          - name : TableColumn<Process, String>
          - processTable : TableView<Process>
          - ram : TableColumn<Process, Double>
          - ramG : Gauge
          + cpuClick()
          + initialize()
          + memClick()
          + startTable()
          ~ exitApp()
          ~ infoClick()
          ~ processSelected()
      }
    }
  }
  

  Controller.ControllerCPU .up.|> javafx.fxml.Initializable
  Controller.ControllerMem .up.|> javafx.fxml.Initializable
  Controller.ControllerUI .up.|> javafx.fxml.Initializable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
