@startuml

title __MODEL's Class Diagram__\n

    namespace odel {
      class Model.Alarm {
          - alarmFile : File
          - br : BufferedReader
          - command : String
          - cpuThreshold : Double
          - doCommand : boolean
          - doEmail : boolean
          - email : String
          {static} - instance : Alarm
          - memThreshold : Double
          - path : String
          - running : boolean
          - textArea : TextArea
          + Alarm()
          + appendToAlarmFile()
          {static} + getInstance()
          + printText()
          + read()
          + sendByCommand()
          + setCommand()
          + setCpuThreshold()
          + setDoCommand()
          + setDoEmail()
          + setEmail()
          + setMemThreshold()
          + verifyProcesses()
          - init()
          - open()
          - verifyCPU()
          - verifyMEM()
      }
    }

  

    namespace odel {
      class Model.Email {
          - recipient : String
          - sender : String
          - session : Session
          + Email()
          + send()
          - init()
      }
    }
  

    namespace odel {
      class Model.Process {
          - cpu : Double
          - mem : Double
          + Process()
          + getCpu()
          + getMem()
      }
    }

    namespace odel {
      class Model.Tradutor {
          {static} + linhaProcess()
          {static} - getCPU()
          {static} - getRAM()
      }
    }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
